Update ci_build_merge_manual.yml

diff --git a/.github/workflows/ci_build_merge_manual.yml b/.github/workflows/ci_build_merge_manual.yml
--- a/.github/workflows/ci_build_merge_manual.yml
+++ b/.github/workflows/ci_build_merge_manual.yml
@@ -100,27 +100,31 @@ jobs:
           # Pull the latest history to avoid conflicts, using ours strategy to favor current changes
           git pull origin gh-storage -s recursive -X ours --allow-unrelated-histories
       
-          # Attempt to push with retries
-          MAX_RETRIES=5
+          MAX_RETRIES=3
           DELAY_BETWEEN_RETRIES=5
           RETRY_COUNT=0
           PUSH_SUCCESS=0
-          
-          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
-            if git push -f origin gh-storage; then
-              PUSH_SUCCESS=1
-              break
-            else
-              RETRY_COUNT=$((RETRY_COUNT+1))
-              echo "Push failed, attempt $RETRY_COUNT/$MAX_RETRIES. Retrying in $DELAY_BETWEEN_RETRIES seconds..."
-              sleep $DELAY_BETWEEN_RETRIES
-              
-              # Fetch the latest remote changes and rebase again
-              git fetch origin gh-storage
-              git rebase origin/gh-storage
+    
+          # Loop to retry the force push if it fails
+          until git push -f origin gh-storage; do
+            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+              echo "Push failed after $MAX_RETRIES retries."
+              exit 1
             fi
+            RETRY_COUNT=$((RETRY_COUNT+1))
+            echo "Push failed, attempt $RETRY_COUNT/$MAX_RETRIES. Retrying in $DELAY_BETWEEN_RETRIES seconds..."
+            sleep $DELAY_BETWEEN_RETRIES
+            # Fetch the latest remote changes before retrying
+            git fetch origin gh-storage
+            git checkout -B gh-storage origin/gh-storage
+            git rm --cached -r .
+            git clean -fdx
+            # Re-add the notebook and commit it
+            git add ${{ matrix.notebook }}
+            git commit -m "Replace executed notebook ${{ matrix.notebook }}"
           done
         fi
+        
   generate_html:
     needs: tests
     runs-on: ubuntu-20.04
