Update ci_build_merge_manual.yml

diff --git a/.github/workflows/ci_build_merge_manual.yml b/.github/workflows/ci_build_merge_manual.yml
--- a/.github/workflows/ci_build_merge_manual.yml
+++ b/.github/workflows/ci_build_merge_manual.yml
@@ -96,43 +96,37 @@ jobs:
         git commit -m "Storing executed notebook ${{ matrix.notebook }}"
         echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
-    - name: Commit and push modifications to target branch with retries
-      run: |
-        MAX_RETRIES=3
-        RETRY_COUNT=0
+- name: Commit and push modifications to target branch with retries
+  run: |
+    MAX_RETRIES=3
+    RETRY_COUNT=0
 
-        until [ $RETRY_COUNT -eq $MAX_RETRIES ]
-        do
-          # Make sure gh-storage is up-to-date with origin
-          git fetch origin gh-storage
+    until [ $RETRY_COUNT -eq $MAX_RETRIES ]
+    do
+      # Fetch the latest state of the gh-storage branch
+      git fetch origin gh-storage
 
-          # Directly checkout and reset to the latest state from the remote
-          git checkout -B gh-storage origin/gh-storage
+      # Rebase your changes onto the latest state
+      git rebase origin/gh-storage
 
-          # Checkout the specific notebook from our previously saved commit
-          git checkout $COMMIT_SHA -- ${{ matrix.notebook }}
-
-          # Commit the change
-          git commit -m "Storing executed notebook ${{ matrix.notebook }}"
-
-          # Try forcefully pushing
-          git push -f origin gh-storage
+      # Try pushing
+      git push origin gh-storage
           
-          # Check the exit status of the push command
-          if [ $? -eq 0 ]; then
-            echo "Push successful!"
-            exit 0
-          else
-            echo "Force push failed. Retrying..."
-            RETRY_COUNT=$((RETRY_COUNT + 1))
-            sleep 10  # increased the sleep time to give any other competing pushes time to finish
-          fi
-        done
+      # Check the exit status of the push command
+      if [ $? -eq 0 ]; then
+        echo "Push successful!"
+        exit 0
+      else
+        echo "Push failed. Retrying..."
+        RETRY_COUNT=$((RETRY_COUNT + 1))
+        sleep 5
+      fi
+    done
 
-        echo "Failed to push after $MAX_RETRIES attempts."
-        exit 1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    echo "Failed to push after $MAX_RETRIES attempts."
+    exit 1
+  env:
+    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
 
