Update ci_build_merge_manual.yml

diff --git a/.github/workflows/ci_build_merge_manual.yml b/.github/workflows/ci_build_merge_manual.yml
--- a/.github/workflows/ci_build_merge_manual.yml
+++ b/.github/workflows/ci_build_merge_manual.yml
@@ -97,18 +97,23 @@ jobs:
           git add ${{ matrix.notebook }}
           git commit -m 'Added executed notebook ${{ matrix.notebook }}'
           ATTEMPTS_LEFT=3
-          until [ $ATTEMPTS_LEFT -lt 1 ]
+          while [ $ATTEMPTS_LEFT -gt 0 ]
           do
             git pull origin gh-storage -s recursive -X ours --allow-unrelated-histories
-            git push origin gh-storage 2>&1 | tee output.log
-            if grep -q "Updates were rejected because the remote contains work" output.log; then
-              echo "Push failed due to conflicting remote changes. Remaining attempts: $ATTEMPTS_LEFT"
-              let "ATTEMPTS_LEFT--"
-              sleep 5
+            git push origin gh-storage
+            PUSH_EXIT_CODE=$?
+            if [ $PUSH_EXIT_CODE -ne 0 ]; then
+              echo "Push failed with exit code $PUSH_EXIT_CODE. Remaining attempts: $ATTEMPTS_LEFT"
+              let "ATTEMPTS_LEFT=ATTEMPTS_LEFT-1"
+              sleep $((RANDOM % 10 + 5))  # Random sleep between 5 to 15 seconds to spread out the retries
             else
               break
             fi
           done
+          if [ $ATTEMPTS_LEFT -eq 0 ]; then
+            echo "Failed to push after multiple attempts."
+            exit 1
+          fi
         fi
   generate_html:
     needs: execute_notebooks
