Update ci_build_merge_manual.yml

diff --git a/.github/workflows/ci_build_merge_manual.yml b/.github/workflows/ci_build_merge_manual.yml
--- a/.github/workflows/ci_build_merge_manual.yml
+++ b/.github/workflows/ci_build_merge_manual.yml
@@ -100,12 +100,40 @@ jobs:
         git checkout gh-storage
         git checkout @{-1} ${{ matrix.notebook }}
   
-    - name: Commit and push modifications to target branch
+    - name: Commit and push modifications to target branch with retries
       run: |
-        git commit -m "Storing executed notebook ${{ matrix.notebook }}"
-        git push origin gh-storage --force
+        MAX_RETRIES=3
+        RETRY_COUNT=0
+
+        until [ $RETRY_COUNT -eq $MAX_RETRIES ]
+        do
+          # Reset the branch to the latest remote state
+          git fetch origin gh-storage:gh-storage
+          git checkout gh-storage
+
+          # Reapply the change
+          git checkout @{-1} ${{ matrix.notebook }}
+          git commit -m "Storing executed notebook ${{ matrix.notebook }}"
+
+          # Try pushing
+          git push origin gh-storage
+          
+          # Check the exit status of the push command
+          if [ $? -eq 0 ]; then
+            echo "Push successful!"
+            exit 0
+          else
+            echo "Push failed. Retrying..."
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+            sleep 5
+          fi
+        done
+
+        echo "Failed to push after $MAX_RETRIES attempts."
+        exit 1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   generate_html:
     needs: execute_notebooks
     runs-on: ubuntu-latest
