Update ci_builder.yml

diff --git a/.github/workflows/ci_builder.yml b/.github/workflows/ci_builder.yml
--- a/.github/workflows/ci_builder.yml
+++ b/.github/workflows/ci_builder.yml
@@ -22,6 +22,95 @@ env:
 
  
 jobs:
+  identify-changed-notebooks:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Fetch all history
+
+      - name: Get list of changed .ipynb files
+        id: get_files
+        run: |
+          git fetch origin gh-storage:gh-storage
+          changed_files=$(git diff --name-only ${{ github.sha }} gh-storage -- '*.ipynb')
+          echo "changed_files=$changed_files" >> $GITHUB_ENV
+
+      - name: Create matrix for changed notebooks
+        id: set-matrix
+        run: |
+          readarray -t notebooks <<< "$changed_files"
+          notebooks_json=$(echo "${notebooks[@]}" | jq -Rc 'split("\n")[:-1]')
+          echo "::set-output name=matrix::{\"include\": $(echo "$notebooks_json" | jq -c '[.[] | {notebook: .}]')}"
+
+  execute-notebooks:
+    needs: identify-changed-notebooks
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    strategy:
+      matrix: ${{fromJson(needs.identify-changed-notebooks.outputs.matrix)}}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python ${{ inputs.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ inputs.python-version }}
+        
+      - name: Install Jupyter and nbconvert
+        run: pip install nbconvert
+
+      - name: Prepare and execute notebook
+        run: |
+          NOTEBOOK_DIR=$(dirname ${{ matrix.notebook }})
+          
+          # Check if pre-requirements.sh exists and run it
+          if [ -f "${NOTEBOOK_DIR}/pre-requirements.sh" ]; then
+            echo "Running pre-requirements.sh in ${NOTEBOOK_DIR}"
+            chmod +x ${NOTEBOOK_DIR}/pre-requirements.sh
+            (cd $NOTEBOOK_DIR; ./pre-requirements.sh)
+          fi
+
+          # Install Python dependencies from requirements.txt if it exists
+          if [ -f "${NOTEBOOK_DIR}/requirements.txt" ]; then
+            echo "Installing requirements from ${NOTEBOOK_DIR}/requirements.txt"
+            pip install -r ${NOTEBOOK_DIR}/requirements.txt
+          fi
+
+          # Execute the notebook
+          jupyter nbconvert --to notebook --execute --inplace ${{ matrix.notebook }}
+      - name: Commit modified file on current branch
+        run: |
+          git config user.name 'CI Bot'
+          git config user.email 'action@github.com'
+          git add ${{ matrix.notebooks }}
+          git commit -m "Storing executed notebook ${{ matrix.notebooks }}"
+  
+      - name: Checkout only the file to the target branch
+        run: |
+          git checkout -f gh-storage
+          git checkout @{-1} ${{ matrix.notebooks }}
+  
+      - name: Commit and push modifications to target branch
+        run: |
+          git commit -m "Storing executed notebook ${{ matrix.notebooks }}"
+  
+          MAX_RETRIES=5
+          RETRY_DELAY=10s
+          for i in $(seq 1 $MAX_RETRIES); do
+            git push origin gh-storage --force && break || {
+              echo "Push $i failed... waiting $RETRY_DELAY"
+              sleep $RETRY_DELAY
+            }
+          done
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   generate_html:
     runs-on: ubuntu-latest
     permissions:
@@ -34,8 +123,18 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: ${{ inputs.python-version }}
-        
+
+    - name: Install Jupyter and nbconvert
+      run: |
+        pip install nbconvert
+
+    # Remaining steps for installing dependencies and building HTML
     - name: Install dependencies
+      run: |
+        pip install ghp-import jupyter-book==v0.15.1 myst-nb astroid nbval jsonschema==4.6.0
+        PATH="${PATH}:${HOME}/.local/bin"
+          
+    - name: Install dependencies for HTML build
       run: |
         pip install ghp-import
         pip install jupyter-book
@@ -47,7 +146,28 @@ jobs:
         ## test to bypass the jupyter-book lower version
         pip install jsonschema==4.6.0
         PATH="${PATH}:${HOME}/.local/bin"
+        
+    - name: Checkout only the file to the target branch
+      run: |
+        git checkout -f gh-storage
+        git checkout @{-1} ${{ matrix.notebooks }}
 
+    - name: Commit and push modifications to target branch
+      run: |
+        git commit -m "Storing executed notebook ${{ matrix.notebooks }}"
+
+        MAX_RETRIES=5
+        RETRY_DELAY=10s
+        for i in $(seq 1 $MAX_RETRIES); do
+          git push origin gh-storage --force && break || {
+            echo "Push $i failed... waiting $RETRY_DELAY"
+            sleep $RETRY_DELAY
+          }
+        done
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+        
     - name: Build HTML
       run: |
         git fetch
