Update ci_build_merge_manual.yml

diff --git a/.github/workflows/ci_build_merge_manual.yml b/.github/workflows/ci_build_merge_manual.yml
--- a/.github/workflows/ci_build_merge_manual.yml
+++ b/.github/workflows/ci_build_merge_manual.yml
@@ -93,37 +93,38 @@ jobs:
         # Configure Git with the GitHub Actions identity
         git config --global user.name "GitHub Actions"
         git config --global user.email "actions@github.com"
-
-        # Checkout the gh-storage branch
-        git fetch origin gh-storage
-        git checkout -b temp-branch origin/gh-storage
-    
-        # Add the executed notebook
+        git config pull.rebase false
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "actions@github.com"
+        git checkout -b gh-storage
         git add ${{ matrix.notebook }}
-        
-        # Commit the changes. This will create a new commit each time it's run, even if there are no changes.
-        git commit -m "Update executed notebook"
-        
-        # Force push the update to gh-storage. We use --force-with-lease to ensure we do not overwrite other changes inadvertently.
-        RETRIES=3
-        DELAY=10
-        until git push --force-with-lease origin temp-branch:gh-storage; do
-          if [ $RETRIES -le 0 ]; then
-            echo "Retry limit reached, not trying anymore."
-            exit 1
+        git commit -m 'Added executed notebook ${{ matrix.notebook }}'
+    
+        # Pull the latest history to avoid conflicts, using ours strategy to favor current changes
+        git pull origin gh-storage -s recursive -X ours --allow-unrelated-histories
+    
+        # Attempt to push with retries
+        MAX_RETRIES=3
+        DELAY_BETWEEN_RETRIES=5
+        RETRY_COUNT=0
+        PUSH_SUCCESS=0
+    
+        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+          if git push -f origin gh-storage; then
+            PUSH_SUCCESS=1
+            break
+          else
+            RETRY_COUNT=$((RETRY_COUNT+1))
+            echo "Push failed, attempt $RETRY_COUNT/$MAX_RETRIES. Retrying in $DELAY_BETWEEN_RETRIES seconds..."
+            sleep $DELAY_BETWEEN_RETRIES
           fi
-          echo "Push failed, retrying in $DELAY seconds..."
-          sleep $DELAY
-          let RETRIES-=1
-          DELAY=$(( DELAY * 2 ))
-          # Fetch the latest gh-storage updates to avoid overwriting concurrent changes
-          git fetch origin gh-storage
-          git reset --hard origin/gh-storage
-          # Re-add the executed notebook and commit again
-          git add ${{ matrix.notebook }}
-          git commit -m "Retry update of executed notebook"
         done
-      
+    
+        if [ $PUSH_SUCCESS -ne 1 ]; then
+          echo "Push failed after $MAX_RETRIES retries."
+          exit 1
+        fi
+
       
   generate_html:
     runs-on: ubuntu-latest
