Update ci_build_merge_manual.yml

diff --git a/.github/workflows/ci_build_merge_manual.yml b/.github/workflows/ci_build_merge_manual.yml
--- a/.github/workflows/ci_build_merge_manual.yml
+++ b/.github/workflows/ci_build_merge_manual.yml
@@ -96,37 +96,37 @@ jobs:
         git commit -m "Storing executed notebook ${{ matrix.notebook }}"
         echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
-- name: Commit and push modifications to target branch with retries
-  run: |
-    MAX_RETRIES=3
-    RETRY_COUNT=0
-
-    until [ $RETRY_COUNT -eq $MAX_RETRIES ]
-    do
-      # Fetch the latest state of the gh-storage branch
-      git fetch origin gh-storage
-
-      # Rebase your changes onto the latest state
-      git rebase origin/gh-storage
-
-      # Try pushing
-      git push origin gh-storage
-          
-      # Check the exit status of the push command
-      if [ $? -eq 0 ]; then
-        echo "Push successful!"
-        exit 0
-      else
-        echo "Push failed. Retrying..."
-        RETRY_COUNT=$((RETRY_COUNT + 1))
-        sleep 5
-      fi
-    done
-
-    echo "Failed to push after $MAX_RETRIES attempts."
-    exit 1
-  env:
-    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Commit and push modifications to target branch with retries
+      run: |
+        MAX_RETRIES=3
+        RETRY_COUNT=0
+    
+        until [ $RETRY_COUNT -eq $MAX_RETRIES ]
+        do
+          # Fetch the latest state of the gh-storage branch
+          git fetch origin gh-storage
+    
+          # Rebase your changes onto the latest state
+          git rebase origin/gh-storage
+    
+          # Try pushing
+          git push origin gh-storage
+              
+          # Check the exit status of the push command
+          if [ $? -eq 0 ]; then
+            echo "Push successful!"
+            exit 0
+          else
+            echo "Push failed. Retrying..."
+            RETRY_COUNT=$((RETRY_COUNT + 1))
+            sleep 5
+          fi
+        done
+    
+        echo "Failed to push after $MAX_RETRIES attempts."
+        exit 1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
 
