Update ci_runner.yml

diff --git a/.github/workflows/ci_runner.yml b/.github/workflows/ci_runner.yml
--- a/.github/workflows/ci_runner.yml
+++ b/.github/workflows/ci_runner.yml
@@ -123,6 +123,14 @@ jobs:
       - name: Commit and push modifications to target branch
         run: |
           git commit -m "Storing executed notebook ${{ matrix.notebooks }}"
-          git push origin gh-storage --force
+
+          MAX_RETRIES=5
+          RETRY)_DELAY=10s
+          for i in $(seq 1 $MAX_RETRIES); do
+            git push origin gh-storage --force && break || {
+              echo "Push $i failed... waiting $RETRY_DELAY"
+              sleep $RETRY_DELAY
+            }
+          done
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
