Update ci_scheduled.yml

diff --git a/.github/workflows/ci_scheduled.yml b/.github/workflows/ci_scheduled.yml
--- a/.github/workflows/ci_scheduled.yml
+++ b/.github/workflows/ci_scheduled.yml
@@ -14,6 +14,20 @@ on:
         required: true
         type: string
 jobs:
+  find-notebooks:
+    runs-on: ubuntu-latest
+    outputs:
+      notebooks: ${{ steps.notebooks.outputs.notebooks }}
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Find all notebooks
+      id: notebooks
+      run: |
+        notebooks=$(find notebooks/ -type f -name "*.ipynb")
+        echo "::set-output name=notebooks::[\"$(echo $notebooks | sed 's/ /", "/g')\"]"
+
   test-notebooks:
     needs: find-notebooks
     runs-on: ubuntu-latest
@@ -93,3 +107,48 @@ jobs:
         else
           echo "Monitor process already terminated or not running."
         fi
+
+  handle-resource-failure:
+    if: ${{ needs.test-notebooks.outputs.resource_failure == 'true' }}  # Use output from previous job
+    runs-on: jwst-pipeline-notebooks-16gb  # 16GB runner for retry
+    needs: test-notebooks  # Ensure this depends on the test-notebooks job
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ inputs.python-version }}
+
+    - name: Install Python packages
+      run: |
+        python -m pip install --upgrade pip
+        pip install jupyter nbconvert
+        notebook_dir=$(dirname "${{ needs.find-notebooks.outputs.notebooks }}")
+        pip install -r "$notebook_dir/requirements.txt"
+
+    - name: Retry the notebook execution
+      run: |
+        notebook_path="${{ needs.find-notebooks.outputs.notebooks }}"
+        jupyter nbconvert --to notebook --execute "$notebook_path"
+
+  handle-resource-failure-32gb:
+    if: ${{ needs.handle-resource-failure.result == 'failure' }}
+    runs-on: jwst-pipeline-notebooks-32gb  # 32GB runner for retry
+    needs: handle-resource-failure
+    steps:
+    - name: Retry the notebook execution on a larger runner (32GB)
+      run: |
+        notebook_path="${{ needs.find-notebooks.outputs.notebooks }}"
+        jupyter nbconvert --to notebook --execute "$notebook_path"
+
+  fail-test:
+    if: ${{ needs.handle-resource-failure-32gb.result == 'failure' }}
+    runs-on: ubuntu-latest
+    needs: handle-resource-failure-32gb
+    steps:
+    - name: Fail the test if all attempts fail
+      run: |
+        echo "Memory or disk usage exceeded 90% on all runners. Failing the test."
+        exit 1
